let musicDB = [
  {
    id: 0,
    name: "Shakedown",
    author_name: "Clarx",
    img: "shakedown.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Clarx - Shakedown [NCS Release].mp3",
    attribution: {
      song: "Clarx - Shakedown [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: "http://ncs.io/Shakedown",
      stream: "http://youtu.be/qJT0mc3q6Lg",
    },
  },
  {
    id: 1,
    name: "Games Worldbeat",
    author_name: "Bernardo R.",
    img: "notAvailable.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "mixkit-games-worldbeat-466.mp3",
    attribution: {
      song: "Games Worldbeat",
      musicBy: "mixkit",
      download: null,
      stream: null,
    },
  },
  {
    id: 2,
    name: "OverMyHead",
    author_name: " ROY KNOX",
    img: "over-my-head-1602154826-mOiKzOJDe6.jpg",
    lang: "ENGLISH",
    type: "electronic",
    timesPlayed: 0,
    musicName: "ROY KNOX -  Over My Head (Feat. Mike Robert) [NCS Release].mp3",
    attribution: {
      song: "ROY KNOX - Over My Head (Feat. Mike Robert) [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: "http://ncs.io/OverMyHead",
      stream: null,
    },
  },
  {
    id: 3,
    name: "Want You (feat. Sara Skinner)",
    author_name: "Subtact, Sara Skinner",
    img: "want-you-feat-sara-skinner-1586956276-s4lOrfrHQj.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Subtact - Want You (feat. Sara Skinner) [NCS Release].mp3",
    attribution: {
      song: "Subtact - Want You (feat. Sara Skinner) [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: "http://ncs.io/WantYou",
      stream: "http://youtu.be/Pww31vN_1QY",
    },
  },
  {
    id: 4,
    name: "Apocalypse",
    author_name: "Midranger",
    img: "apocalypse-1600776027-tsCmgK4gEU.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Midranger - Apocalypse [NCS Release].mp3",
    attribution: {
      song: "Midranger - Apocalypse [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: "http://ncs.io/Apocalypse",
      stream: "http://youtu.be/Whw1sWDpAvE",
    },
  },
  {
    id: 5,
    name: "Alive",
    author_name: "Neoni, N3WPORT",
    img: "alive.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "N3WPORT - Alive (feat. Neoni) [NCS Release].mp3",
    attribution: {
      song: "N3WPORT - Alive (feat. Neoni) [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: "http://ncs.io/NAlive",
      stream: "http://youtu.be/vJAcXd_UtWQ",
    },
  },
  {
    id: 6,
    name: "Impact Moderato",
    author_name: "Kevin MacLeod",
    img: "notAvailable.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "impact.mp3",
    attribution: {
      song: "Impact Moderato",
      musicBy: "Kevin MacLeod",
      download: null,
      stream: null,
    },
  },
  {
    id: 7,
    name: "Impact Moderato 2",
    author_name: "Kevin MacLeod",
    img: "notAvailable.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "impact2.mp3",
    attribution: {
      song: "Impact Moderato",
      musicBy: "Kevin MacLeod",
      download: null,
      stream: null,
    },
  },
  {
    id: 8,
    name: "Ignite",
    author_name: "Tom wilson, Heuse",
    img: "ignite-1600419626-nHn4WXY79q.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "Heuse & Tom Wilson - Ignite [NCS Release].mp3",
    attribution: {
      song: "Heuse & Tom Wilson - Ignite [NCS Release]",
      musicBy: "NoCopyrightSounds",
      download: "http://ncs.io/Ignite",
      stream: "http://youtu.be/zbqgv0mMfwk",
    },
  },
  {
    id: 9,
    name: "On My Way",
    author_name: "Alan Walker",
    img: "1.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "1.mp3",
    attribution: {
      song: "Alan Walker - On My Way",
      musicBy: "Alan Walker",
      download: null,
      stream: null,
    },
  },
  {
    id: 10,
    name: "Alan Walker-Fade",
    author_name: "Alan Walker",
    img: "2.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "2.mp3",
    attribution: {
      song: "Alan Walker-Fade",
      musicBy: "Alan Walker",
      download: null,
      stream: null,
    },
  },
  {
    id: 11,
    name: "Cartoon-on & on",
    author_name: "Deniel Levi ",
    img: "3.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "3.mp3",
    attribution: {
      song: "Deniel Levi - Cartoon-on & on",
      musicBy: "Deniel Levi",
      download: null,
      stream: null,
    },
  },
  {
    id: 12,
    name: "Warriyo - Mortals",
    author_name: "Mortals",
    img: "4.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "4.mp3",
    attribution: {
      song: "Mortals - Warriyo - Mortals",
      musicBy: "Mortals",
      download: null,
      stream: null,
    },
  },
  {
    id: 13,
    name: "Ertugrul Gazi",
    author_name: "Ertugrul",
    img: "5.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "5.mp3",
    attribution: {
      song: "Ertugrul Gazi",
      musicBy: "Ertugrul",
      download: null,
      stream: null,
    },
  },
  {
    id: 14,
    name: "Electronic Music",
    author_name: "Electro",
    img: "6.jpg",
    lang: "ENGLISH",
    timesPlayed: 0,
    type: "electronic",
    musicName: "6.mp3",
    attribution: {
      song: "Electronic Music",
      musicBy: "Electro",
      download: null,
      stream: null,
    },
  },
  {
    id: 15,
    name: "Agar Tum Sath Ho",
    author_name: "Tamashaa",
    img: "7.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "7.mp3",
    attribution: {
      song: "Agar Tum Sath Ho",
      musicBy: "Tamashaa",
      download: null,
      stream: null,
    },
  },
  {
    id: 16,
    name: "Suna Hai",
    author_name: "Neha Kakker",
    img: "8.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "8.mp3",
    attribution: {
      song: "Suna Hai",
      musicBy: "Neha Kakker",
      download: null,
      stream: null,
    },
  },
  {
    id: 17,
    name: "Dilbar",
    author_name: "Satyameva Jayate",
    img: "9.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "9.mp3",
    attribution: {
      song: "Dilbar",
      musicBy: "Satyameva Jayate",
      download: null,
      stream: null,
    },
  },
  {
    id: 18,
    name: "Duniya",
    author_name: "Luka Chupi",
    img: "10.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "10.mp3",
    attribution: {
      song: "Duniya",
      musicBy: "Luka Chupi",
      download: null,
      stream: null,
    },
  },
  {
    id: 19,
    name: "Lagdi Lahore Di",
    author_name: "Street Dancer 3D",
    img: "11.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "11.mp3",
    attribution: {
      song: "Lagdi Lahore Di",
      musicBy: "Street Dancer 3D",
      download: null,
      stream: null,
    },
  },
  {
    id: 20,
    name: "Putt Jatt Da",
    author_name: "Putt Jatt Da",
    img: "12.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "12.mp3",
    attribution: {
      song: "Putt Jatt Da",
      musicBy: "Putt Jatt Da",
      download: null,
      stream: null,
    },
  },
  {
    id: 21,
    name: "Baarishein",
    author_name: "Atif Aslam",
    img: "13.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "13.mp3",
    attribution: {
      song: "Baarishein",
      musicBy: "Atif Aslam",
      download: null,
      stream: null,
    },
  },
  {
    id: 22,
    name: "Vaaste",
    author_name: "Dhvani Bhanushali",
    img: "14.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "14.mp3",
    attribution: {
      song: "Vaaste",
      musicBy: "Dhvani Bhanushali",
      download: null,
      stream: null,
    },
  },
  {
    id: 23,
    name: "Lut Gaye",
    author_name: "Jubin Nautiyal",
    img: "15.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "15.mp3",
    attribution: {
      song: "Lut Gaye",
      musicBy: "Jubin Nautiyal",
      download: null,
      stream: null,
    },
  },
  {
    id: 24,
    name: "Tu Meri Jindagi ",
    author_name: "Jubin Nautiyal",
    img: "16.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "16.mp3",
    attribution: {
      song: "Tu Meri Jindagi ",
      musicBy: "Jubin Nautiyal",
      download: null,
      stream: null,
    },
  },
  {
    id: 25,
    name: "Batao Yaad Hai Tu",
    author_name: "Rahat Fateh Ali Khan",
    img: "17.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "17.mp3",
    attribution: {
      song: "Batao Yaad Hai Tu",
      musicBy: "Rahat Fateh Ali Khan",
      download: null,
      stream: null,
    },
  },
  {
    id: 26,
    name: "Mere Dhol Judai",
    author_name: "Ali Sethi Seha Gill",
    img: "18.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "electronic",
    musicName: "18.mp3",
    attribution: {
      song: "Mere Dhol Judai",
      musicBy: "Ali Sethi Seha Gill",
      download: null,
      stream: null,
    },
  },

  {
    id: 27,
    name: "Eh Munde Pagal N",
    author_name: "Ap Dhillon , Gurinder",
    img: "19.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "19.mp3",
    attribution: {
      song: "Eh Munde Pagal N",
      musicBy: "Ap Dhillon , Gurinder",
      download: null,
      stream: null,
    },
  },
  {
    id: 28,
    name: "Naina ashq na ho",
    author_name: "Arjit Singh",
    img: "A1.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "A1.mp3",
    attribution: {
      song: "Naina ashq na ho",
      musicBy: "Arjit Singh",
      download: null,
      stream: null,
    },
  },
  {
    id: 29,
    name: "Khairiyat",
    author_name: "Arjit Singh",
    img: "A2.jpg",
    lang: "Hindi",
    timesPlayed: 0,
    type: "instrumental",
    musicName: "A2.mp3",
    attribution: {
      song: "Khairiyat",
      musicBy: "Arjit Singh",
      download: null,
      stream: null,
    },
  },
];

export default musicDB;
/*let musicDB = [
  {
    id:0,
    name:"Left Foot Up Right Foot Slide",
    author_name: "Yung Nazty",
    img: "left_foot_up_right_foot_slide.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"left_foot_up_right_foot_slide.mp3"
  },
  {
    id:1,
    name: "Intentions (feat. Quavo)",
    author_name: "Justin Bieber",
    img: "intentions.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"intentions.mp3"
  },
  {
    id:2,
    name: "Naina Da Kya Kasoor",
    author_name: "Amit Trivedi",
    img: "naina_da_kya_kasoor.jpg",
    lang:"HINDI",
    timesPlayed:0,
    musicName:"Naina_da_kya_kasoor.mp3"
  },
  {
    id:3,
    name: "Señorita",
    author_name: "Shawn Mendes",
    img: "senorita.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"senorita.mp3"
  },
  {
    id:4,
    name: "Memories",
    author_name: "Maroon 5",
    img: "memories.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"memories.mp3"
  },
  {
    id:5,
    name: "Skechers",
    author_name: "DripReport",
    img: "skechers.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"Skechers.mp3"
  },
  {
    id:6,
    name: "Sunflower - Spider-Man: Into the Spider-Verse",
    author_name: "Post Malone",
    img: "sunflower.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"Sunflower.mp3"
  },
  {
    id:7,
    name: "I Can’t Get Enough",
    author_name: "benny blanco, Selena Gomez, J Balvin, Tainy",
    img: "i_cant_get_enough.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"i_cant_get_enough.mp3"
  },
  {
    id:8,
    name: "Old Town Road",
    author_name: "Lil Nas X",
    img: "old_town_road.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"old_town_road.mp3"
  },
  {
    id:9,
    name: "Beautiful Stillness",
    author_name: "Billy-Joe",
    img: "beautiful_stillness.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"Beautiful_Stillness.mp3"
  },
  {
    id:10,
    name: "death bed (coffee for your head)",
    author_name: "Powfu",
    img: "death_bed.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"death_bed.mp3"
  },
  {
    id:11,
    name: "Halka Halka (From \"Fanney Khan\")",
    author_name: "Sunidhi Chauhan",
    img: "halka_halka_suroor.jpg",
    lang:"HINDI",
    timesPlayed:0,
    musicName:"halka_halka_suroor.mp3"
  },
  {
    id:12,
    name: "Kudi Nu Nachne De (From \"Angrezi Medium\")",
    author_name: "Vishal Dadlani",
    img: "kudi_nu_nachne_de.jpg",
    lang:"HINDI",
    timesPlayed:0,
    musicName:"kudi_nu_nachne_de.mp3"
  },
  {
    id:13,
    name: "Illegal Weapon 2.0",
    author_name: "Jasmine Sandlas",
    img: "illeagal_weapon_2.jpg",
    lang:"PUBJABI",
    timesPlayed:0,
    musicName:"illeagal_weapon_2.mp3"
  },
  {
    id:14,
    name: "Genda Phool (feat. Payal Dev)",
    author_name: "Badshah",
    img: "genda_phool.jpg",
    lang:"BENGALI",
    timesPlayed:0,
    musicName:"genda_phool.mp3"
  },
  {
    id:15,
    name: "Yaar Mod Do",
    author_name: "Guru Randhawa",
    img: "yaar_mod_do.jpg",
    lang:"PUNJABI",
    timesPlayed:0,
    musicName:"yaar_mod_do.mp3"
  },
  {
    id:16,
    name: "Shayad",
    author_name: "Pritam",
    img: "shayad.jpg",
    lang:"HINDI",
    timesPlayed:0,
    musicName:"shayad.mp3"
  },
  {
    id:17,
    name: "Without Me",
    author_name: "Halsey",
    img: "without_me.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"without_me.mp3"
  },
  {
    id:18,
    name: "Buttabomma - Telugu",
    author_name: "Armaan Malik",
    img: "buttabomma.jpg",
    lang:"TELUGU",
    timesPlayed:0,
    musicName:"ButtaBomma.mp3"
  },
  {
    id:19,
    name: "Coda",
    author_name: "Jakob Ahlbom",
    img: "coda.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"coda.mp3"
  },
  {
    id:20,
    name: "Khairiyat",
    author_name: "Arijit Singh",
    img: "khairiyat.jpg",
    lang:"HINDI",
    timesPlayed:0,
    musicName:"khairiyat.mp3"
  },
  {
    id:21,
    name: "Haan Main Galat",
    author_name: "Pritam",
    img: "haan_mai_galat.jpg",
    lang:"HINDI",
    timesPlayed:0,
    musicName:"haan_mai_galat.mp3"
  },
  {
    id:22,
    name: "Mere Liye Tum Kaafi Ho (From \"Shubh Mangal Zyada Saavdhan\")",
    author_name: "Ayushmann Khurrana",
    img: "mere_liiye_tum_kaafi_ho.jpg",
    lang:"HINDI",
    timesPlayed:0,
    musicName:"mere_liiye_tum_kaafi_ho.mp3"
  },
  {
    id:23,
    name: "Fracture",
    author_name: "Jakob Ahlbom",
    img: "fracture.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"fracture.mp3"
  },
  {
    id:24,
    name: "Ghungroo (From \"War\")",
    author_name: "Arijit Singh",
    img: "ghungroo.jpg",
    lang:"HINDI",
    timesPlayed:0,
    musicName:"ghungroo.mp3"
  },
  {
    id:25,
    name: "Happier",
    author_name: "Marshmello",
    img: "happier.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"happier.mp3"
  },
  {
    id:26,
    name: "Namo Namo",
    author_name: "Amit Trivedi",
    img: "namo_namo.jpg",
    lang:"HINDI",
    timesPlayed:0,
    musicName:"namo_namo.mp3"
  },
  {
    id:27,
    name: "Faded",
    author_name: "Alan Walker",
    img: "faded.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"Faded_Alan_Walker.mp3"
  },
  {
    id:28,
    name: "I Don't Care (with Justin Bieber)",
    author_name: "Ed Sheeran",
    img: "i_dont_care.jpg",
    lang: "ENGLISH",
    timesPlayed:0,
    musicName:"i_dont_care.mp3"
  }
]
export default musicDB;*/
